name: 📱 Simple PathTracker Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: ☕ Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 🏗️ Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: 🔧 Make gradlew executable
      run: chmod +x ./gradlew

    - name: 📱 Build APK
      run: ./gradlew assembleDebug --no-daemon

    - name: 📤 Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: PathTracker-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: 📊 Build Summary
      run: |
        echo "🎉 PathTracker APK built successfully!"
        if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
          echo "📍 APK Location: app/build/outputs/apk/debug/app-debug.apk"
          echo "📦 APK Size: $(du -h app/build/outputs/apk/debug/app-debug.apk | cut -f1)"
          echo "✅ APK is ready for download!"
        else
          echo "❌ APK not found"
          ls -la app/build/outputs/apk/debug/ || echo "Debug directory not found"
        fi